name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install robotframework
        pip3 install robotframework-appiumlibrary
        pip3 install Appium-Python-Client
        npm install -g appium
        appium -v

    - name: Give Gradlew Permission
      run: chmod +x ./gradlew

    - name: Download dependencies
      run: ./gradlew build --stacktrace

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: '30.0.3'

    - name: Create Emulator
      run: |
        avdmanager create avd -n test -k "system-images;android-30;default;x86_64" --force
        $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
        adb wait-for-device
        adb shell settings put global window_animation_scale 0
        adb shell settings put global transition_animation_scale 0
        adb shell settings put global animator_duration_scale 0

    - name: Start Appium Server
      run: appium &

    - name: Run Robot Framework Tests
      run: robot "test.robot"
