name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install robotframework
        pip3 install robotframework-appiumlibrary
        pip3 install Appium-Python-Client
        npm install -g appium
        appium -v

    - name: Download dependencies
      run: ./gradlew build --stacktrace

    - name: Start Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        script: ./gradlew connectedCheck
        target: default
        arch: x86_64
        profile: Nexus 6
        disable-animations: true

    - name: Start Appium Server
      run: appium &

    - name: Run Robot Framework Tests
      run: robot path/to/your/tests
